In [ ]:
import numpy as np

In [5]:
np.__version__

'2.2.3'

In [ ]:
np.array([1, 2, 3]), type(np.array([1, 2, 3]))

array([1, 2, 3])

In [ ]:
np.array([1,2 ,3, "hello"])

In [6]:
array = np.array([1, 2, 3])
array, array.dtype

(array([1, 2, 3]), dtype('int64'))

In [20]:
array = np.array([1, 2, 3], dtype=np.int8)
array, array.dtype

(array([1, 2, 3], dtype=int8), dtype('int8'))

In [9]:
2 ** 8 - 1

255

In [10]:
bin(2**8)

'0b100000000'

In [12]:
bin(2**8-1)

'0b11111111'

In [19]:
array = np.array([1, 2, 3, 127], dtype=np.int8)
array

array([  1,   2,   3, 127], dtype=int8)

In [22]:
array = np.array([1, 2, 3, 128, ], dtype=np.uint8)
array

array([  1,   2,   3, 128], dtype=uint8)

In [23]:
array = np.array([1, 2, 3, 128, 255], dtype=np.uint8)
array

array([  1,   2,   3, 128, 255], dtype=uint8)