In [1]:
import numpy as np

In [4]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [9]:
array.min(), array.max(), min(array), max(array)

(np.int64(10), np.int64(500), np.int64(10), np.int64(500))

In [8]:
array.sum(), sum(array)

(np.int64(1338), np.int64(1338))

In [7]:
array.mean()

np.float64(111.5)

In [ ]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array.min(), array.argmin()

(np.int64(10), np.int64(3))

In [12]:
array.max(), array.argmax()

(np.int64(500), np.int64(2))

In [13]:
l = [23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30]
l.index(30)

5

In [14]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [15]:
array[array > 100]

array([500, 310, 101, 203])

In [16]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [17]:
array[-1]

np.int64(30)

In [18]:
array[-2:]

array([203,  30])

In [19]:
array[array % 2 == 0]

array([500,  10,  40,  30, 310,  20,  30,  30])

In [21]:
array[(array % 2 == 0) & (array > 50)]

array([500, 310])

In [22]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [23]:
array[(array % 3) | (array < 40)]

array([ 10, 500, 500,  41,  41,  41,  41,  10,  41, 500, 500,  41])